{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf400
{\fonttbl\f0\fswiss\fcharset0 ArialMT;\f1\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\csgray\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl400\partightenfactor0

\f0\fs29\fsmilli14667 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 apiVersion: extensions/v1beta1
\f1\fs24 \

\f0\fs29\fsmilli14667 kind: Ingress
\f1\fs24 \

\f0\fs29\fsmilli14667 metadata:
\f1\fs24 \

\f0\fs29\fsmilli14667  \'a0name: spikey-website-ingress
\f1\fs24 \

\f0\fs29\fsmilli14667 spec:
\f1\fs24 \

\f0\fs29\fsmilli14667  \'a0backend:
\f1\fs24 \

\f0\fs29\fsmilli14667  \'a0\'a0\'a0serviceName: spikey-website
\f1\fs24 \

\f0\fs29\fsmilli14667  \'a0\'a0\'a0servicePort: 80
\f1\fs24 \cb1 \
}